"""Euler45_TriPentHex"""
"""
Triangular, pentagonal, and hexagonal
Problem 45 
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
"""

tris=[1,3,6,10,15]
pents=[1,5,12,22,25]
hexs=[1,6,15,28,45]
def assemble(maxim):
    i=6
    while i<=maxim:
        tris.append(int(i*(i+1)/2))
        pents.append(int(i*(3*i-1)/2))
        hexs.append(int(i*(2*i-1)))
        i+=1
    for item in tris:
        if item in pents and item in hexs:
            print(item)
    #return [tris,pents,hexs]
    
outs=assemble(100000) #--> 1,40755,1533776805...#CORRECT